# See https://github.com/actions/labeler

"🚨 action":
  - .github/workflows/**

"🚧 astro":
  - "starlight/astro.config.mjs"

"📀 assets":
  - starlight/src/assets/**
  - starlight/public/**

"📚 content":
  - starlight/src/content/docs/**

"🈳 dictionary":
  - .github/actions/spelling/**

"✒️ documentation":
  - "**/README.md"

"🌏 i18n":
  - starlight/src/content/docs/en/**

"📦 package":
  - "starlight/package.json"

"🏯 styles":
  - starlight/src/styles/**
