packages:
  - "starlight"

allowBuilds:
  esbuild: false
  sharp: true

minimumReleaseAgeExclude:
  - astro-contributors
  - starlight-group-pages
  - starlight-sidebar-topics-dropdown
  - starlight-view-modes
