apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: i18n-mutanuq
  namespace: i18n-mutanuq
spec:
  secretName: i18n-mutanuq
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "i18n-mutanuq.trueberryless.org"
