apiVersion: apps/v1
kind: Deployment
metadata:
  name: i18n-mutanuq
  namespace: mutanuq
  labels:
    app: i18n-mutanuq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: i18n-mutanuq
  template:
    metadata:
      labels:
        app: i18n-mutanuq
    spec:
      containers:
        - name: i18n-mutanuq
          image: "trueberryless/i18n-mutanuq:main-234a37ae1d469684d76db87589ab12822ca82d18"
          imagePullPolicy: Always
