apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mutanuq
  namespace: mutanuq
spec:
  secretName: mutanuq
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "mutanuq.trueberryless.org"
