apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutanuq
  namespace: mutanuq
  labels:
    app: mutanuq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mutanuq
  template:
    metadata:
      labels:
        app: mutanuq
    spec:
      containers:
        - name: mutanuq
          image: 'trueberryless/mutanuq:main-9c134afb68657532c7c2d5d4b7588484e80c7f28'
          imagePullPolicy: Always
