name: Docker Image Push Always

on:
  push:
  merge_group:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: trueberryless/mutanuq-always
  NODE_VERSION: 18

jobs:  
  docker-push-image:
    if: contains(github.event.head_commit.message, 'version') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest  
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV          

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME}}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :wave: Preview of this PR: [https://mutanuq-${{ env.BRANCH_NAME }}.trueberryless.org/de/](https://mutanuq-${{ env.BRANCH_NAME }}.trueberryless.org/de/)
