name: Lunaria PR Overview

on:
    # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
    pull_request_target:
        types: [opened, synchronize]
        branches: [main]
        paths:
            - "starlight/**"

# Allow this job to clone the repository and comment on the pull request
permissions:
    contents: read
    pull-requests: write

jobs:
    lunaria-overview:
        name: Generate Lunaria Overview
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # Necessary for Lunaria to work properly
                  # Makes the action clone the entire git history
                  fetch-depth: 0

            - name: Setup PNPM
              uses: pnpm/action-setup@v3
              with:
                  package_json_file: ./starlight/package.json

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
                  cache-dependency-path: ./starlight/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install
              shell: bash
              working-directory: ./starlight

            - name: Generate Lunaria Overview
              uses: yanthomasdev/lunaria-action@v0.1.0
              with:
                  working-directory: starlight
